name: Fetch KPLC Planned Outages
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r services/prediction/requirements.txt
      - name: Fetch KPLC outages
        run: python services/kplc/scraper/fetch_kplc_planned_outages.py models/planned_outages.json
      - name: Commit updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/planned_outages.json
          git commit -m "Update planned outages [skip ci]" || echo "No changes"
          git push

