name: Train Outage Model

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/services/prediction/train_from_parquet.py'
      - 'src/services/prediction/requirements.txt'
      - 'src/services/prediction/**'
      - 'src/models/**'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r src/services/prediction/requirements.txt
      - name: Train
        run: |
          python src/services/prediction/train_from_parquet.py --input ./src/storm_and_outage_merged_2014_2023.parquet --output ./src/models
      - name: Commit model artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add src/models/**
          git commit -m "Update trained model artifacts" || echo "No changes to commit"
          git push

